version: "3.9"

services:
  deployi:
    image: deployi:latest
    container_name: deployi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    volumes:
      - ./data:/app/data
    restart: always
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

  api:
    image: deployi:latest
    container_name: api
    depends_on:
      - deployi
    working_dir: /app/api
    command: ["node", "dist/index.js"]
    restart: always
    env_file:
      - .env.production

  schedules:
    image: deployi:latest
    container_name: schedules
    depends_on:
      - api
    working_dir: /app/schedules
    command: ["node", "dist/index.js"]
    restart: always
    env_file:
      - .env.production

  server:
    image: deployi:latest
    container_name: server
    depends_on:
      - api
    working_dir: /app/server
    command: ["node", "dist/index.js"]
    restart: always
    env_file:
      - .env.production

  monitoring:
    image: deployi:latest
    container_name: monitoring
    depends_on:
      - server
    working_dir: /app/monitoring
    command: ["/app/monitoring/main"]
    restart: always
