version: "3.9"

services:
  deployi:
    build:
      context: .
      dockerfile: Dockerfile
      target: deployi
    image: deployi-v1:0.7
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - internal

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: deployi
      POSTGRES_PASSWORD: ezeslucky
      POSTGRES_DB: deployi
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - internal

networks:
  internal:

volumes:
  pgdata:
