packages:
  - apps/api
  - apps/deployi
  - apps/monitoring
  - apps/schedules
  - packages/server

onlyBuiltDependencies:
  - '@tree-sitter-grammars/tree-sitter-yaml'
  - bcrypt
  - tree-sitter
  - tree-sitter-json
