http:
  routers:
    deployi-router-app:
      rule: Host(`deployi.docker.localhost`) && PathPrefix(`/`)
      service: deployi-service-app
      entryPoints:
        - web
  services:
    deployi-service-app:
      loadBalancer:
        servers:
          - url: http://deployi:3000
        passHostHeader: true
