name: Deploy to EC2

on:
  push:
    branches: [ candly ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: 13.49.95.183
          REMOTE_USER: ubuntu
          SOURCE: "./"
          TARGET: "/var/www/deployi"

      - name: Run post-deploy script
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 13.49.95.183
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/deployi
            npm install
            npm run build
            pm2 restart all
