name: Pull Request

on:
  pull_request:
    branches: [mainn]

env:
  HUSKY: 0

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.18.0
          cache: "yarn"
      - run: corepack enable  # Ensures modern Yarn works
      - run: yarn install --frozen-lockfile
      - run: yarn biome ci
      - run: yarn typecheck
